vich_uploader:
  db_driver: orm

  mappings:
    car:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/public/uploads"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
